export enum Penalties {
  ABUSE = 'Abuse',
  BOARD = 'Board',
  CHARG = 'Charging',
  CROSS = 'Cross Check',
  BDYCH = 'Body Checking',
  CHECK = 'Checking',
  CHEB = 'Checking From Behind',
  DELAY = 'Delay of Game',
  ELBOW = 'Elbow',
  FIGHT = 'Fight',
  HOST = 'Holding the Stick',
  HOLD = 'Holding',
  HOOK = 'Hooking',
  INTRF = 'Interference',
  KICK = 'Kick',
  KNEE = 'Knee',
  MATCH = 'Match',
  ROUGH = 'Roughing',
  SLASH = 'Slashing',
  SPEAR = 'Spearing',
  TOOM = 'Too Many Men',
  TRIP = 'Tripping',
  UNSP = 'Un-Sportsman like',
  MISC = 'Misconduct',
  HIST = 'High Stick',
  THROWSTICK = 'Throwing Stick',
  ILLEQUIP = 'Illegal Equipment',
}

export const penaltyDurations = [2, 4, 5, 10, 20, 25];
